apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
spec:
  replicas: 1  # Initial replicas
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
      - name: rag-service
        image: rag-service:latest  
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: MAX_BATCH_SIZE
          value: "16"